// src/App.vue
<script setup lang="ts">
import { onMounted } from "vue";

import SectionComponent from "@/components/sections/section-component.vue";
import IconContainer from "./components/icon-container.vue";
import ClockComponent from "./components/clock-component.vue";
import ContainerComponent from "./components/container-component.vue";
import AddBookmarkSheetComponent from "@/components/bookmarks/add-bookmark-sheet-component.vue";
import EditBookmarkSheetComponent from "@/components/bookmarks/edit-bookmark-sheet-component.vue";
import AddSectionComponent from "./components/sections/add-section-component.vue";
import EditSectionComponent from "./components/sections/edit-section-component.vue";
import Sidebar from "./components/sidebar/sidebar-component.vue";


import useTheme from "./lib/hooks/use-theme";
import useWallpaper from "./lib/hooks/use-wallpaper";
import useSections from "./lib/hooks/use-sections";
import { openSidebarContext } from "./lib/context/sidebar-context";
import sections from "./lib/context/section-context";
import { Settings } from "lucide-vue-next";

const { loadSections } = useSections();
const { loadWallpaper } = useWallpaper();
const { loadTheme } = useTheme();

onMounted(() => {
  loadSections();
  loadWallpaper();
  loadTheme();
});
</script>

<template>
  <ContainerComponent>
    <AddSectionComponent />
    <EditSectionComponent />
    <AddBookmarkSheetComponent />
    <EditBookmarkSheetComponent />
    <Sidebar />

    <nav class="flex justify-between items-center w-full p-2">
      <div />
      <ClockComponent />
      <div class="mt-1 hover:cursor-pointer" @click="openSidebarContext.onOpen()">
        <Settings />
      </div>
    </nav>

    <section class="flex flex-col items-center justify-center w-full overflow-y-scroll">
      <IconContainer />
      <div class="w-2/3 md:w-fit p-6 md:p-2 border border-primary rounded-lg space-y-2 2xl:space-y-4 bg-background">
        <SectionComponent v-for="section in sections" :key="section.label" :section="section" />
      </div>
    </section>
    <div />
  </ContainerComponent>
</template>

// src/app/page.tsx
"use client";

import {ClockComponent} from "@/components/clock";
import {Container} from "@/components/container";
import IconComponent from "@/components/icon";
import {MiddleIconContainer} from "@/components/middle-icon-container";
import {SectionCard} from "@/features/sections/components/card";

import {useSectionsStore} from "@/features/sections/sections-store";
import {openSidebar} from "@/store/open-sidebar";

export default function Home() {
  const {sections} = useSectionsStore();
  const {onOpen} = openSidebar();

  return (
    <Container>
      <nav className="inline-flex justify-between items-center w-full p-2">
        <div></div>
        <ClockComponent />
        <div>
          <button onClick={onOpen}>
            <IconComponent icon="Settings" size="sm" className="transition-all hover:rotate-180 hover:cursor-pointer" />
          </button>
        </div>
      </nav>

      <div className="flex flex-col items-center justify-center w-full overflow-y-scroll">
        <MiddleIconContainer />

        <div className="w-2/3 md:w-fit p-6 md:p-2 border border-primary rounded-lg space-y-2 2xl:space-y-4 bg-card">
          {Object.keys(sections).map((section) => (
            <SectionCard key={sections[section].id} section={sections[section]} />
          ))}
        </div>
      </div>
      <div></div>
    </Container>
  );
}
