// src/components/Container.svelte
<script lang="ts">
  import userWallpaper from "$lib/context/wallpaper-context";
  import { onDestroy } from "svelte";

  let container: HTMLDivElement;

  const updateBackground = (wallpaper: string | null) => {
    container.style.backgroundImage = wallpaper
      ? `url(${wallpaper})`
      : "var(--gradient-bg)";
  };

  const unsub = userWallpaper.subscribe((wallpaper) => {
    if (container) {
      updateBackground(wallpaper);
    }
  });
  onDestroy(() => {
    unsub();
  });
</script>

<div class="container" bind:this={container}>
  <div class="hidden__container" />
  <slot />
</div>

<style>
  .container {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: 100%;
    position: relative;
    color: var(--fg);
    background-position: center;
    background-size: cover;
    overflow: hidden;
  }

  .hidden__container {
    position: absolute;
    background: rgba(0, 0, 0, 0.6);
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    backdrop-filter: blur(4px);
  }
</style>

// src/components/container-component.vue
<script setup lang="ts">
import userWallpaper from "@/lib/context/wallpaper-context";
import { ref, watch } from "vue";

const container = ref<HTMLDivElement | null>(null);

const updateBackground = (wallpaper: string | null) => {
  if (container.value) {
    container.value.style.backgroundImage = wallpaper
      ? `url(${wallpaper})`
      : "var(--gradient)";
  }
};

watch(() => userWallpaper.value, (newWallpaper) => {
  updateBackground(newWallpaper);
}, { immediate: true });
</script>

<template>
  <div class="img_container relative flex flex-col items-center justify-center w-full h-screen overflow-hidden" ref="container">
    <div class="absolute inset-0 bg-black/60 backdrop-blur-md"/>
    <div class="relative z-10 w-full h-full space-y-5 lg:space-y-20">
      <slot />
    </div>
  </div>
</template>

<style scoped>
.img_container {
  background-position: center;
  background-size: cover;
}
</style>
